### ISSUE TITLE
reduce size of contact pictures

### ISSUE THREAD

**Issue by danielskatz** [SORSE/sorse.github.io#200]
Some of the contact pictures on https://github.com/SORSE/sorse.github.io/tree/master/assets/images, at least for me and for Debbie Carter are quite large and take time to load in https://sorse.github.io/contact/ - they should probably be downscaled if they are just going to be used at this small size.

**Comment by vsoch** [comment]
There's a nice bot that can handle this for you: https://github.com/marketplace/imgbot.

**Comment by Chilipp** [comment]
thanks @danielskatz and @vsoch! Good catch :smiley: I just installed the bot for the SORSE organization

**Comment by danielskatz** [comment]
by size, I meant to reduce the dimensions, which also would reduce the number of bytes.

**Comment by Chilipp** [comment]
as stated in #201, the images are pretty big in total (see graphic below) which is why the contact page downloads about 23MB of data. This is too much, particularly for mobile devices. I'll decrease the size of all avatar images and make a new PR

![image](https://user-images.githubusercontent.com/9960249/85836710-53143780-b797-11ea-95d3-89d8ad85f8c3.png)
